[package]
name = "facet-macro-parse"
version = "0.32.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

description = "Parser for facet derive macros - takes TokenStream and returns parsed type representations"

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet-macro-types = { version = "0.32.2", path = "../facet-macro-types" }
proc-macro2 = "1"
quote = { workspace = true } #unified

[dev-dependencies]
