[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
publish = false

[features]
ci = [] # CI feature

[dependencies]
facet = { path = "../facet" }
facet-json = { path = "../facet-json" }
ratatui = "0.29"
crossterm = "0.29"
