[package]
name = "xtask"
version = "0.43.0"
edition = "2024"
rust-version = "1.90.0"
publish = false

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[features]

[dependencies]
benchmark-defs = { path = "../tools/benchmark-defs", version = "0.43.0" }
facet = { path = "../facet", version = "0.43.1", features = ["all-impls", "doc"] }
facet-args = { path = "../facet-args", version = "0.43.1" }
facet-json = { path = "../facet-json", version = "0.43.1" }

[lints]
workspace = true
