[package]
name = "xtask"
version = "0.33.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[features]

[dependencies]
benchmark-defs = { path = "../tools/benchmark-defs", version = "0.33.0" }
facet = { workspace = true, features = ["bytes", "camino", "chrono", "doc", "jiff02", "net", "nonzero", "ordered-float", "time", "ulid", "uuid"] } #unified
facet-args = { path = "../facet-args", version = "0.33.0" }
facet-json = { path = "../facet-json", version = "0.33.0", features = ["axum"] }
miette = { workspace = true }
