[package]
name = "proto-ext-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
proto-attr = { path = "../proto-attr" }
proto-attr-macros = { path = "../proto-attr-macros" }

[lints]
workspace = true
