[package]
name = "facet-shapelike"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2.10.0"
facet = { path = "../facet", version = "0.31.8", features = ["alloc"] }
facet-core = { path = "../facet-core", version = "0.31.8", features = ["alloc"] }
facet-macros = { path = "../facet-macros", version = "0.31.8" }
facet-postcard = { path = "../facet-postcard", version = "0.1.0" }
facet-reflect = { path = "../facet-reflect", default-features = false }

[dev-dependencies]
facet-json = { path = "../facet-json", version = "0.31.0" }
facet-kdl = { path = "../facet-kdl", version = "0.31.0" }
facet-assert = { path = "../facet-assert", version = "0.31.0" }
facet-xml = { path = "../facet-xml", version = "0.31.0" }
facet-args = { path = "../facet-args", version = "0.31.0" }
