[package]
name = "facet-format-json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
corosensei = { version = "0.3", optional = true }
facet-core = { path = "../facet-core", features = ["auto-traits", "bytes", "camino", "chrono", "fn-ptr", "indexmap", "jiff02", "net", "nonzero", "num-complex", "ordered-float", "ruint", "simd", "time", "tuples-12", "ulid", "url", "uuid"] }
facet-format = { path = "../facet-format" }
facet-json = { path = "../facet-json", features = ["axum"] }
facet-reflect = { path = "../facet-reflect", features = ["miette"] }
futures-io = { version = "0.3", optional = true }
tokio = { version = "1", default-features = false, optional = true, features = ["io-util"] }

[dev-dependencies]
facet = { workspace = true, features = ["doc", "net"] } #unified
facet-format-suite = { path = "../facet-format-suite", features = ["third-party"] }
indoc = { workspace = true } #unified
libtest-mimic = "0.8.1"

[[test]]
name = "format_suite"
harness = false

[features]
default = []
streaming = ["dep:corosensei", "facet-json/streaming", "std"]
std = ["facet-json/std"]
tokio = ["streaming", "facet-json/tokio", "dep:tokio"]
futures-io = ["streaming", "facet-json/futures-io", "dep:futures-io"]
