[package]
name = "facet-macros"
version = "0.31.8"
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Proc macro for deriving the 'Facet' trait in facet"
keywords = [
    "reflection",
    "introspection",
    "serialization",
    "deserialization",
    "derive",
]
categories = ["development-tools", "encoding"]

[lib]
proc-macro = true

[features]
function = ["facet-macros-impl/function"]

[dependencies]
facet-macros-impl = { version = "0.31.8", path = "../facet-macros-impl" }

# cf. https://hachyderm.io/@epage/114141126315983016
[target.'cfg(any())'.dependencies]
facet-core = { path = "../facet-core", version = "0.31.8" }
