[package]
name = "facet-kdl"
version = "0.31.0"
edition = "2024"
rust-version = "1.88.0"
license = "MIT or Apache-2.0"
description = "KDL serialization and deserialization for Facet types"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs/meta/highlight.html"]

[features]
std = ["alloc", "facet-core/std", "facet-reflect/std"]
alloc = ["facet-core/alloc", "facet-reflect/alloc"]
default = ["std"]
slow-tests = [] # Enable slow tests (compile tests)

[dependencies]
log = "0.4"
facet-core = { path = "../facet-core" }
facet-reflect = { path = "../facet-reflect", features = ["miette"] }
facet-solver = { path = "../facet-solver" }
kdl = "6.5.0"
miette = "7"

[dev-dependencies]
facet = { path = "../facet" }
facet-core = { path = "../facet-core", features = ["camino"] }
facet-pretty = { path = "../facet-pretty" }
facet-showcase = { path = "../facet-showcase" }
facet-testhelpers = { path = "../facet-testhelpers" }
tempfile = "3"
camino = "1"
miette = { version = "7", features = ["fancy", "syntect-highlighter"] }
indoc = "2.0.7"
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }
