[package]
name = "facet-inspect"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allows inspecting types that implement Facet"
keywords = ["reflection", "introspection", "facet", "peek", "poke"]
categories = ["development-tools", "rust-patterns"]

[dependencies]
facet = { path = "../facet", version = "0.28.0" }
facet-reflect = { path = "../facet-reflect", version = "0.28.0" }
