[package]
name = "benchmark-defs"
version = "0.35.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = { workspace = true }
facet-args = { path = "../../facet-args" }
facet-format-kdl = { path = "../../facet-format-kdl" }
