[package]
name = "benchmark-defs"
version = "0.42.0"
edition = "2024"
rust-version = "1.90.0"
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = { version = "0.42.0", path = "../../facet" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[lints]
workspace = true
