[package]
name = "benchmark-defs"
version = "0.43.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"

[lints]
workspace = true
