[package]
name = "facet-reflect2-afl"
version = "0.0.0"
publish = false
edition = "2024"

[features]
cov = []

[dependencies]
afl = "0.15"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.facet]
path = "../../facet"

[dependencies.facet-core]
path = "../../facet-core"

[dependencies.facet-reflect2]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
