[package]
name = "proto-ext"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Example extension crate using proto-attr grammar"

[dependencies]
proto-attr.workspace = true
proto-attr-macros.workspace = true

[dev-dependencies]
tempfile = "3"
facet-showcase = { path = "../../../facet-showcase" }  # relative to proto-attr/crates/proto-ext

[features]
default = []
slow-tests = []
nightly = ["proto-attr/nightly"]

[lints]
workspace = true
