[package]
name = "benchmark-generator"
version = "0.43.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[[bin]]
name = "benchmark-generator"
path = "src/main.rs"

[dependencies]
benchmark-defs = { workspace = true }
regex = "1.12.2"
serde_json = { workspace = true }

[lints]
workspace = true
