[package]
name = "benchmark-generator"
version = "0.41.0"
edition = "2024"
rust-version = "1.90.0"
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[[bin]]
name = "benchmark-generator"
path = "src/main.rs"

[dependencies]
benchmark-defs = { path = "../benchmark-defs", version = "0.42.0" }
regex = "1.12.2"
serde_json = { workspace = true }

[lints]
workspace = true
